services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    container_name: project_backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./data:/app/data
    #   - ./config:/app/config
    networks:
      - project_network
    restart: unless-stopped
# .env
# bo volume
# reverse proxy: nginx
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: project_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/v1
    depends_on:
      - backend
    networks:
      - project_network
    # volumes:
    #   - ./data:/app/data
    #   - ./config:/app/config
    restart: unless-stopped

networks:
  project_network: