[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chatbot"
version = "0.1.0"
description = "Graph-based AI app with FastAPI and LangGraph"
authors = [
    { name = "nam861836" }
]

requires-python = ">=3.10, <4.0"
dependencies = [
    "fastapi[standard]>=0.110.0",
    "uvicorn>=0.29.0",
    "langchain-core",
    "langgraph",
    "langchain-openai",
    "langchain-tavily",
    "langchain-community",
    "langsmith",
    "pypdf",
    "rank-bm25",
    "pydantic>=2.0.0",
    "langgraph-checkpoint",
    "langgraph-checkpoint-mongodb",
    "redis",
    "streamlit>=1.48.1",
    "requests>=2.32.4",
]
