[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chatbot"
version = "0.1.0"
description = "Graph-based AI app with FastAPI and LangGraph"
authors = [
    { name = "nam861836" }
]

requires-python = ">=3.10, <4.0"
dependencies = [
    "streamlit",
    "requests"
]


